// Kazalo pesmarice: naslov (kot v bazi) -> stran v pesmarica.pdf
// Uporabljeno samo za povezavo "skoči na pravo stran", brez besedil.
// Posodobljeno: nova pesmarica (september 2026, z dodano "Jesen V Meni").
window.PESMARICA_PAGES = [
  // ---- Angleške ----
  {raw:"Lean On Me - Bill Withers", page:3},
  {raw:"Perfect - Ed Sheeran", page:4},
  {raw:"Simply The Best - Tina Turner", page:5},
  {raw:"Angel - Shaggy", page:6},
  {raw:"Mercy - Duffy", page:7},
  {raw:"I Love Rock'n'Roll - Joan Jett", page:8},
  {raw:"Sympathy For The Devil - The Rolling Stones", page:9},
  {raw:"Angel - Robbie Williams", page:10},
  {raw:"Valerie - Amy Winehouse", page:11},
  {raw:"Hallelujah - Jeff Buckley", page:12},
  {raw:"Sex Bomb - Tom Jones", page:14},
  {raw:"Should I Stay Or Should I Go - The Clash", page:15},
  {raw:"I Will Survive - Gloria Gaynor", page:16},
  {raw:"Jailhouse Rock - Elvis Presley", page:17},
  {raw:"Crazy Little Thing Called Love - Queen", page:18},
  {raw:"Hit The Road Jack - Ray Charles", page:19},
  {raw:"Shook Me All Night Long - AC/DC", page:20},
  {raw:"Proud Mary - Tina Turner", page:21},

  // ---- Španske ----
  {raw:"La Bamba - Los Lobos", page:22},

  // ---- Italijanske ----
  {raw:"Sara Perche Ti Amo - Ricchi e Poveri", page:23},

  // ---- Slovenske ----
  {raw:"Ti Znaš - Slavko Ivančič", page:24},
  {raw:"Dolgo Nisva Pila - Hamo in Bučar", page:25},
  {raw:"Ob Tebi Bom Ostal - Jan Plestenjak", page:26},
  {raw:"Ko Mene Več Ne Bo - Slavko Ivančič", page:27},
  {raw:"Kar Je Res Je Res - Faraoni", page:28},
  {raw:"BIT - Zmelkoow", page:29},
  {raw:"Črta - Slavko Ivančič", page:30},
  {raw:"Gravitacija - Zmelkoow", page:31},

  // ---- Ex-Yu ----
  {raw:"Klinka - S.A.R.S.", page:32},
  {raw:"Čija Si - Toše Proeski", page:33},
  {raw:"Verujem Ne Verujem - Bajaga", page:34},
  {raw:"Dva Put Sam Umra - Oliver Dragojević", page:35},
  {raw:"Ljubavna - Parni Valjak", page:36},
  {raw:"Vjeruj U Ljubav - Oliver Dragojević", page:37},
  {raw:"Jesen V Meni - Parni Valjak", page:38},
  {raw:"Nije Htjela - Oliver Dragojević", page:39},
  {raw:"Tišina - Bajaga", page:40},
  {raw:"Ako Voliš Me - Oliver Dragojević", page:41},
  {raw:"Ribari - Vinko Coce", page:42},
  {raw:"Gore Dole - Bajaga", page:43},
  {raw:"Uhvati Ritam - Parni Valjak", page:44},
  {raw:"Godine Prolaze - Bajaga", page:45},
  {raw:"Kad Ti Ljubav Ime Prozove - Plavi Orkestar", page:46},
  {raw:"Činim Pravo Stvar - Gibonni", page:47},
  {raw:"Diteljina S Četiri Lista - Dalmatino", page:48},
  {raw:"Odlazim - Plavi Orkestar", page:49},
  {raw:"Lepa Janja - Bajaga", page:50},
  {raw:"To Mi Radi - Crvena Jabuka", page:51},
  {raw:"Tekila Gerila - Bajaga", page:52},
  {raw:"Zelena Trava Doma Mog - Riblja Čorba", page:53},
  {raw:"Kad Sam Bio Mlad - Riblja Čorba", page:54},
  {raw:"Ca Ce Mi Copacabana - Oliver Dragojević", page:55},
  {raw:"Moja - Toše Proeski", page:56},
  {raw:"Možeš Imat Moje Tjelo - Zabranjeno Pušenje", page:57},
  {raw:"Ruža Hrvatska - Prljavo Kazalište", page:58},
  {raw:"Tamara - Boris Novković", page:59},
  {raw:"Blagom Onom Ko Te Ima - Tony Cetinski", page:60},
  {raw:"Kad Si Rekla Da Me Voliš - Dino Merlin", page:61},
  {raw:"Ako Te Pitaju - Petar Grašo", page:62},
  {raw:"Bez Tebe - Oliver Dragojević", page:63},
  {raw:"Libar - Gibonni", page:64},
  {raw:"U Ljubav Vjere Nemam - Oliver Dragojević", page:65},
  {raw:"Dok Je Tebe - Parni Valjak", page:66},
  {raw:"Sve Još Miriše Na Nju - Parni Valjak", page:67},
  {raw:"Lutka - S.A.R.S.", page:68},
  {raw:"Cesarica - Oliver Dragojević", page:69},
  {raw:"Muzika Na Struju - Bajaga", page:70},
  {raw:"Volim I Postojim - Petar Grašo", page:71},
  {raw:"Moji Drugovi - Bajaga", page:72},
  {raw:"Kiše Jesenje - Prljavo Kazalište", page:73},
  {raw:"Ledena - Toše Proeski", page:74},
  {raw:"Za Dobra Stara Vremena - Novi Fosili", page:75},
  {raw:"Zastave - Parni Valjak", page:76},
  {raw:"Ne Zovi Mama Doktora - Prljavo Kazalište", page:77},
  {raw:"Ide Mi U Životu - Danijela Martinović", page:78},
  {raw:"Nedelja - Parni Valjak", page:79},
  {raw:"Lutka Za Bal - Parni Valjak", page:80},
  {raw:"Sanjao Sa Moju Ružicu - Leteči Odred", page:81},
  {raw:"Od Rođendana Do Rođendana - Plavi Orkestar", page:82},
  {raw:"Ko Nam Brani - Petar Grašo", page:83},
  {raw:"Hajde Da Ludujemo - Tajči", page:84},
  {raw:"Frida - Psihomodo Pop", page:85},
  {raw:"Bolje Biti Pijan Nego Star - Plavi Orkestar", page:86},
  {raw:"Hajdemo U Planine - Bijelo Dugme", page:87},
  {raw:"Ako Su To Samo Bile Laži - Plavi Orkestar", page:88},
  {raw:"Đurđevdan - Bijelo Dugme", page:89}
];
