// Kazalo pesmarice: naslov (kot v PDF) -> stran v pesmarica.pdf
// Uporabljeno samo za povezavo "skoči na pravo stran", brez besedil.
window.PESMARICA_PAGES = [
  {raw:"LEAN ON ME - BILL WITHERS", page:4},
  {raw:"BIT - ZMELKOOW", page:5},
  {raw:"SEX BOMB - TOM JONES", page:6},
  {raw:"ČRTA – SLAVKO IVANČIČ", page:7},
  {raw:"HALLELUJAH - JEFF BUCKLEY", page:8},
  {raw:"MOJA - TOŠE PROESKI", page:10},
  {raw:"I WILL SURVIVE - GLORIA GAYNOR", page:11},
  {raw:"DOLGO NISVA PILA – HAMO IN BUČAR", page:12},
  {raw:"MERCY - DUFFY", page:13},
  {raw:"LUTKA ZA BAL - PARNI VALJAK", page:14},
  {raw:"PROUD MARY - TINA TURNER", page:15},
  {raw:"MUZIKA NA STRUJU - BAJAGA", page:16},
  {raw:"ANGEL - SHAGGY", page:17},
  {raw:"IDE MI U ŽIVOTU - DANIJELA MARTINOVIĆ", page:18},
  {raw:"CRAZY LITTLE THING CALLED LOVE - QUEEN", page:19},
  {raw:"LEDENA - TOŠE PROESKI", page:20},
  {raw:"JAILHOUSE ROCK - ELVIS PRESLEY", page:21},
  {raw:"LJUBAVNA - PARNI VALJAK", page:22},
  {raw:"SIMPLY THE BEST - TINA TURNER", page:23},
  {raw:"HAJDE DA LUDUJEMO - TAJCI", page:24},
  {raw:"SARA PERCHE TI AMO - RICCHI E POVERI", page:25},
  {raw:"VOLIM I POSTOJIM - PETAR GRAŠO", page:26},
  {raw:"PERFECT - ED SHEERAN", page:27},
  {raw:"FRIDA - PSIHOMODO POP", page:28},
  {raw:"I LOVE ROCK'N'ROLL", page:29},
  {raw:"MOJI DRUGOVI - BAJAGA", page:30},
  {raw:"SYMPATHY FOR THE DEVIL", page:31},
  {raw:"SVE JOŠ MIRIŠE NA NJU - PARNI VALJAK", page:32},
  {raw:"ANGEL – ROBBIE WILLIAMS", page:33},
  {raw:"VJERUJ U LJUBAV – OLIVER DRAGOJEVIĆ", page:34},
  {raw:"LA BAMBA - LOS LOBOS", page:35},
  {raw:"NEDELJA - PARNI VALJAK", page:36},
  {raw:"SHOOK ME ALL NIGHT LONG – AC/DC", page:37},
  {raw:"SHOULD I STAY OD SHOULD I GO – THE CLASH", page:38},
  {raw:"SHOULD I STAY OR SHOULD I GO – THE CLASH", page:38},
  {raw:"VALERIE – AMY WINHOUSE", page:39},
  {raw:"HIT THE ROAD JACK – RAY CHARLES", page:40},
  {raw:"CESARICA - OLIVER DRAGOJEVIĆ", page:41},
  {raw:"LUTKA - S.A.R.S.", page:42},
  {raw:"AKO TE PITAJU - PETAR GRAŠO", page:43},
  {raw:"KIŠE JESENJE - PRLJAVO KAZALIŠTE", page:44},
  {raw:"KAR JE RES JE RES - FARAONI", page:45},
  {raw:"ČIJA SI - TOŠE PROESKI", page:46},
  {raw:"DITELJINA S ČETIRI LISTA - DALMATINO", page:47},
  {raw:"PETAR GRAŠO - KO NAM BRANI", page:48},
  {raw:"GRAVITACIJA - ZMELKOOW", page:49},
  {raw:"AKO SU TO SAMO BILE LAŽI - PLAVI ORKESTAR", page:50},
  {raw:"HAJDEMO U PLANINE - BIJELO DUGME", page:51},
  {raw:"ĐURĐEVDAN - BIJELO DUGME", page:52},
  {raw:"JESEN V MENI - PARNI VALJAK", page:53},
  {raw:"TI ZNAŠ – SLAVKO IVANČIČ", page:54},
  {raw:"OB TEBI BOM OSTAL - JAN PLESTENJAK", page:55},
  {raw:"KO MENE VEČ NE BO – SLAVKO IVANČIČ", page:56},
  {raw:"GODINE PROLAZE - BAJAGA", page:57},
  {raw:"GORE DOLE - BAJAGA", page:58},
  {raw:"LEPA JANJA - BAJAGA", page:59},
  {raw:"TEKILA GERILA – BAJAGA", page:60},
  {raw:"TIŠINA – BAJAGA", page:61},
  {raw:"VERUJEM NE VERUJEM – BAJAGA", page:62},
  {raw:"TAMARA - BORIS NOVKOVIĆ", page:63},
  {raw:"TO MI RADI - CRVENA JABUKA", page:64},
  {raw:"KAD SI REKLA DA ME VOLIŠ - DINO MERLIN", page:65},
  {raw:"ČINIM PRAVO STVAR - GIBONNI", page:66},
  {raw:"LIBAR - GIBONNI", page:67},
  {raw:"SANJAO SA MOJU RUŽICU - LETEČI ODRED", page:68},
  {raw:"ZA DOBRA STARA VREMENA - NOVI FOSILI", page:69},
  {raw:"AKO VOLIŠ ME - OLIVER DRAGOJEVIĆ", page:70},
  {raw:"BEZ TEBE - OLIVER DRAGOJEVIĆ", page:71},
  {raw:"CA CE MI COPACABANA - OLIVER DRAGOJEVIĆ", page:72},
  {raw:"DVA PUT SAM UMRA - OLIVER DRAGOJEVIĆ", page:73},
  {raw:"NIJE HTJELA - OLIVER DRAGOJEVIĆ", page:74},
  {raw:"U LJUBAV VJERE NEMAM - OLIVER DRAGOJEVIĆ", page:75},
  {raw:"DOK JE TEBE - PARNI VALJAK", page:76},
  {raw:"UHVATI RITAM - PARNI VALJAK", page:77},
  {raw:"ZASTAVE - PARNI VALJAK", page:78},
  {raw:"BOLJE BITI PIJAN NEGO STAR – PLAVI ORKESTAR", page:79},
  {raw:"KAD TI LJUBAV IME PROZOVE - PLAVI ORKESTAR", page:80},
  {raw:"OD ROĐENDANA DO ROĐENDANA - PLAVI ORKESTAR", page:81},
  {raw:"ODLAZIM - PLAVI ORKESTAR", page:82},
  {raw:"NE ZOVI MAMA DOKTORA - PRLJAVO KAZALIŠTE", page:83},
  {raw:"RUŽA HRVATSKA - PRLJAVO KAZALIŠTE", page:84},
  {raw:"KAD SAM BIO MLAD - RIBLJA ČORBA", page:85},
  {raw:"ZELENA TRAVA DOMA MOG - RIBLJA ČORBA", page:86},
  {raw:"KLINKA - S.A.R.S.", page:87},
  {raw:"BLAGOM ONOM KO TE IMA - TONY CETINSKI", page:88},
  {raw:"RIBARI - VINKO COCE", page:89},
  {raw:"MOŽEŠ IMAT MOJE TJELO - ZABRANJENO PUŠENJE", page:90}
];
